/* eslint-disable @next/next/no-img-element */
import { cellText, savedOutputImage, type NotebookCell } from '@/lib/notebooks';

export function Notebook({ cells, figureAlt }: { cells: NotebookCell[]; figureAlt?: string }) {
  return (
    <div className="notebook">
      {cells.map((cell, index) => (
        <section key={index}>
          {cell.cell_type === 'markdown' ? (
            <div className="markdown-cell">
              {cellText(cell.source)
                .split(/\n\s*\n/)
                .map((paragraph, part) =>
                  paragraph.startsWith('## ') ? (
                    <h2 key={part}>{paragraph.slice(3)}</h2>
                  ) : (
                    <p key={part}>{paragraph}</p>
                  ),
                )}
            </div>
          ) : cell.cell_type === 'code' ? (
            <div className="code-cell">
              <div className="cell-label">PYTHON / In [{cell.execution_count ?? ' '}]</div>
              <pre className="code-source">
                <code>{cellText(cell.source)}</code>
              </pre>
              {cell.outputs?.map((output, outputIndex) => {
                const image = savedOutputImage(output);
                return (
                  <div key={outputIndex} className="cell-output">
                    {image ? (
                      <img
                        src={image}
                        alt={figureAlt ?? 'Saved figure generated by this Python cell'}
                      />
                    ) : (
                      <pre>
                        <code>{cellText(output.text ?? output.data?.['text/plain'])}</code>
                      </pre>
                    )}
                  </div>
                );
              })}
            </div>
          ) : (
            <pre className="code-source">{cellText(cell.source)}</pre>
          )}
        </section>
      ))}
    </div>
  );
}
