name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'

      - name: 🛎 Checkout️
        uses: actions/checkout@v3

      - name: 🔧 Install and Build
        run: |
          npm ci
          npm run build-prod
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist